/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animeget;

import main.java.animeget.FetchAnimeData.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        if(2 > args.length) {
            System.out.println("animeget <year> <month>");
            System.exit(1);;
        }
        
        Integer month = Integer.parseInt(args[1]);
        String year = args[0];
        String season = "1";
        switch (month) {
        case 1:
        case 2:
        case 3:
            season = "1";
            break;
        case 4:
        case 5:
        case 6:
            season = "2";
            break;
        case 7:
        case 8:
        case 9:
            season = "3";
            break;
        case 10:
        case 11:
        case 12:
            season = "4";
            break;
        }

        try {
            FetchAnimeData animeData = new FetchAnimeData(year,season);
            ObjectMapper mapper = new ObjectMapper();
            String data = animeData.fetch();
            ArrayList<AnimeData> animeArrayList = mapper.readValue(data,new TypeReference<ArrayList<AnimeData>>(){});
            for (AnimeData anime : animeArrayList) {
                System.out.println(anime.getTitle());
            }
            System.exit(0);
        }catch (IOException exception) {
            System.out.println(exception);
        }
        
    }
}
